// GENERATED by scripts/build-world-map.mjs — do not edit by hand.
// Marker positions in the same projection and viewBox as
// public/images/network-map.svg, with the longitude and latitude they
// came from (the homepage globe places them from those).

export const NETWORK_MAP = {
  width: 1000,
  height: 697,
  origins: [
    {
      "name": "Italy",
      "lon": 12.5,
      "lat": 42.8,
      "x": 136,
      "y": 98.5
    },
    {
      "name": "India",
      "lon": 78.9,
      "lat": 21.8,
      "x": 518.3,
      "y": 240.4
    },
    {
      "name": "Sri Lanka",
      "lon": 80.7,
      "lat": 7.8,
      "x": 537.6,
      "y": 334.8
    },
    {
      "name": "Bangladesh",
      "lon": 90.3,
      "lat": 23.8,
      "x": 580.8,
      "y": 226.8
    },
    {
      "name": "China",
      "lon": 104.5,
      "lat": 33.5,
      "x": 644.7,
      "y": 161.1
    },
    {
      "name": "Vietnam",
      "lon": 106.4,
      "lat": 15.2,
      "x": 681.7,
      "y": 285
    }
  ],
  destination: {"name":"Australia","lon":134.5,"lat":-25.5,"x":827.8,"y":559.3},
} as const;
