// GENERATED by scripts/build-world-map.mjs — do not edit by hand.
// Marker positions in the same projection and viewBox as
// public/images/network-map.svg.

export const NETWORK_MAP = {
  width: 1000,
  height: 697,
  origins: [
    {
      "name": "Italy",
      "x": 136,
      "y": 98.5
    },
    {
      "name": "India",
      "x": 518.3,
      "y": 240.4
    },
    {
      "name": "Sri Lanka",
      "x": 537.6,
      "y": 334.8
    },
    {
      "name": "Bangladesh",
      "x": 580.8,
      "y": 226.8
    },
    {
      "name": "China",
      "x": 644.7,
      "y": 161.1
    },
    {
      "name": "Vietnam",
      "x": 681.7,
      "y": 285
    }
  ],
  destination: {"name":"Australia","x":827.8,"y":559.3},
} as const;
