// GENERATED by scripts/build-service-film.py (see
// docs/SERVICES-FILM-PLAN.md). Don't edit; re-run the script.

// The What We Do film's frames: how many in each set, and which
// belong to each hold and morph ([first, end) per set).
export const SERVICE_FILM = {
  "source": "stand-in",
  "base": "/film/services",
  "version": "ef46b26345",
  "sets": {
    "wide": {
      "width": 1440,
      "height": 810,
      "count": 144
    },
    "tall": {
      "width": 540,
      "height": 960,
      "count": 92
    }
  },
  "segments": [
    {
      "kind": "hold",
      "service": 0,
      "wide": [
        0,
        12
      ],
      "tall": [
        0,
        8
      ]
    },
    {
      "kind": "morph",
      "from": 0,
      "wide": [
        12,
        44
      ],
      "tall": [
        8,
        28
      ]
    },
    {
      "kind": "hold",
      "service": 1,
      "wide": [
        44,
        56
      ],
      "tall": [
        28,
        36
      ]
    },
    {
      "kind": "morph",
      "from": 1,
      "wide": [
        56,
        88
      ],
      "tall": [
        36,
        56
      ]
    },
    {
      "kind": "hold",
      "service": 2,
      "wide": [
        88,
        100
      ],
      "tall": [
        56,
        64
      ]
    },
    {
      "kind": "morph",
      "from": 2,
      "wide": [
        100,
        132
      ],
      "tall": [
        64,
        84
      ]
    },
    {
      "kind": "hold",
      "service": 3,
      "wide": [
        132,
        144
      ],
      "tall": [
        84,
        92
      ]
    }
  ]
} as const;
