// GENERATED by scripts/build-service-film.py (see
// docs/SERVICES-FILM-PLAN.md). Don't edit; re-run the script.

// The What We Do film's frames: how many in each set, and which
// belong to each hold and morph ([first, end) per set).
export const SERVICE_FILM = {
  "source": "media-library/services-film/edit.json",
  "base": "/film/services",
  "version": "b087446e18",
  "sets": {
    "wide": {
      "width": 1440,
      "height": 810,
      "count": 220
    },
    "tall": {
      "width": 540,
      "height": 960,
      "count": 166
    }
  },
  "segments": [
    {
      "kind": "hold",
      "service": 0,
      "wide": [
        0,
        40
      ],
      "tall": [
        0,
        40
      ]
    },
    {
      "kind": "morph",
      "from": 0,
      "wide": [
        40,
        84
      ],
      "tall": [
        40,
        70
      ]
    },
    {
      "kind": "hold",
      "service": 1,
      "wide": [
        84,
        100
      ],
      "tall": [
        70,
        82
      ]
    },
    {
      "kind": "morph",
      "from": 1,
      "wide": [
        100,
        144
      ],
      "tall": [
        82,
        112
      ]
    },
    {
      "kind": "hold",
      "service": 2,
      "wide": [
        144,
        160
      ],
      "tall": [
        112,
        124
      ]
    },
    {
      "kind": "morph",
      "from": 2,
      "wide": [
        160,
        204
      ],
      "tall": [
        124,
        154
      ]
    },
    {
      "kind": "hold",
      "service": 3,
      "wide": [
        204,
        220
      ],
      "tall": [
        154,
        166
      ]
    }
  ]
} as const;
