// GENERATED by scripts/build-service-film.py (see
// docs/SERVICES-FILM-PLAN.md). Don't edit; re-run the script.

// The What We Do film's frames: how many in each set, and which
// belong to each hold and morph ([first, end) per set).
export const SERVICE_FILM = {
  "source": "media-library/services-film/edit.json",
  "base": "/film/services",
  "version": "daf6743ab5",
  "sets": {
    "wide": {
      "width": 1440,
      "height": 810,
      "count": 152
    },
    "tall": {
      "width": 540,
      "height": 960,
      "count": 104
    }
  },
  "segments": [
    {
      "kind": "hold",
      "service": 0,
      "wide": [
        0,
        20
      ],
      "tall": [
        0,
        20
      ]
    },
    {
      "kind": "morph",
      "from": 0,
      "wide": [
        20,
        52
      ],
      "tall": [
        20,
        40
      ]
    },
    {
      "kind": "hold",
      "service": 1,
      "wide": [
        52,
        64
      ],
      "tall": [
        40,
        48
      ]
    },
    {
      "kind": "morph",
      "from": 1,
      "wide": [
        64,
        96
      ],
      "tall": [
        48,
        68
      ]
    },
    {
      "kind": "hold",
      "service": 2,
      "wide": [
        96,
        108
      ],
      "tall": [
        68,
        76
      ]
    },
    {
      "kind": "morph",
      "from": 2,
      "wide": [
        108,
        140
      ],
      "tall": [
        76,
        96
      ]
    },
    {
      "kind": "hold",
      "service": 3,
      "wide": [
        140,
        152
      ],
      "tall": [
        96,
        104
      ]
    }
  ]
} as const;
